zookeeper_1:
  restart: always
  image: mooxe/zookeeper
  net: "host"
  environment:
    MYID: 1
  volumes:
    - .:/root/zookeeper
    - ./zk_1/zoo.cfg:/opt/zookeeper/conf/zoo.cfg:ro
zookeeper_2:
  restart: always
  image: mooxe/zookeeper
  net: "host"
  environment:
    MYID: 2
  volumes:
    - .:/root/zookeeper
    - ./zk_2/zoo.cfg:/opt/zookeeper/conf/zoo.cfg:ro
zookeeper_3:
  restart: always
  image: mooxe/zookeeper
  net: "host"
  environment:
    MYID: 3
  volumes:
    - .:/root/zookeeper
    - ./zk_3/zoo.cfg:/opt/zookeeper/conf/zoo.cfg:ro
